Check for both fzf and mpv

diff --git a/iptv b/iptv
--- a/iptv
+++ b/iptv
@@ -1,8 +1,6 @@
 #!/bin/bash
-if [ ! -x "$(command -v fzf)" ]; then
-  echo "fzf needs to be installed to use iptv."
-  exit 1
-fi
+command -v fzf >/dev/null 2>&1 || { echo >&2 "fzf required but not installed"; exit 1; }
+command -v mpv >/dev/null 2>&1 || { echo >&2 "mpv required but not installed"; exit 1; }
 
 m3u=$1
 
